version: "3.7"
services:
  mock-server:
    image: node:12
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm start"
    working_dir: /mock-server
    volumes:
      - ./mock-server:/mock-server
  frontend:
    image: node:12
    ports:
      - "4200:4200"
    command: bash -c "npm i && npm start -- --host 0.0.0.0"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend